### ISSUE TITLE
New version of container not accepting environment variables from docker-compose file

### ISSUE THREAD

**Issue by rnorris7756** [joshuamorris3/namecheap-ddns-update#2]
Hi, I'm having some issues with the latest version of this container.  Previously, I had set this up to accept the DOMAIN, SUBDOMAINS, and NC_DDNS_PASS values from an environment file.  This is no longer working and the container simply prints the help message and quits.

The directory I'm running from looks like this:
- `docker-compose.yml` (a version 2 compose file)
- `.env`

The `docker-compose.yml` file will automatically read the values in the `.env` file (a feature of docker-compose) and make these values available to the containers.

The entry for the namecheap ddns updater container looks like this:
```
namecheap-ddns:
  image: joshuamorris3/namecheap-ddns-update
  container_name: namecheap_ddns_updater
  restart: unless-stopped
  environment:
    - DOMAIN=${DDNS_DOMAIN}
    - SUBDOMAINS=${DDNS_SUBDOMAIN}
    - INTERVAL=600s
    - NC_DDNS_PASS=${NC_DDNS_PASS}
```

Now, I know that the environment variables are actually being passed correctly because I modified the `namecheap-ddns-update` script to echo `$SUBDOMAINS`, `$DOMAIN`, and `$NC_DDNS_PASS` before printing the help message, and the correct values are printed in the re-built container.

This actually stems from the addition made [here](https://github.com/joshuamorris3/namecheap-ddns-update/blob/d12855e7016428b84cf4088d1905b36b0e8f5947/namecheap-ddns-update#L62), where help is printed if no arguments are given.  Since setting everything via environment variables means there are no arguments, this script will exit here, even if it has the correct information to proceed with the update.  I've tested this by removing the conditional here and using an `.env` file like I normally do and the container runs normally.
