### ISSUE TITLE
Adding a docker-compose file exemple

### ISSUE THREAD

**Issue by mattthhdp** [joshuamorris3/namecheap-ddns-update#5]
Something like
```
namecheap-ddns:
  image: joshuamorris3/namecheap-ddns-update
  container_name: namecheap_ddns_updater
  restart: unless-stopped
  environment:
    - DOMAIN=${DDNS_DOMAIN}
    - SUBDOMAINS=${DDNS_SUBDOMAIN1}
    - SUBDOMAINS=${DDNS_SUBDOMAIN2}
    - INTERVAL=600s
    - NC_DDNS_PASS=${NC_DDNS_PASS}
```
would help
